# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: python

cache:
    directories:
      - ${HOME}/installers

matrix:
  include:
    - os: linux
      dist: precise
      sudo: required
      python:
        - "3.5"
        - "3.6"
      before_install:
        - source .CI/travis/install.sh
        - source .CI/travis/install-arrayfire.sh
        - source .CI/travis/install-khiva.sh
      script:
        - source .CI/travis/build.sh
      after_success:
        - coverage run -m unittest discover tests/unit_tests *_tests.py -f
        - codecov

    - os: linux
      dist: trusty
      sudo: required
      python:
        - "3.5"
        - "3.6"
      before_install:
        - source .CI/travis/install.sh
        - source .CI/travis/install-arrayfire.sh
        - source .CI/travis/install-khiva.sh
      script:
        - source .CI/travis/build.sh
      after_success:
        - coverage run -m unittest discover tests/unit_tests *_tests.py -f
        - codecov

