# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

sudo: required
services:
  - docker

before_install:
  - docker pull shapelets/khiva
  - docker run -i -t -d --name CI shapelets/khiva
  - docker cp . CI:/root

install:
  - docker exec -it CI /bin/bash -c "pip3 install -r requirements.txt"
  - docker exec -it CI /bin/bash -c "pip3 install -r test-requirements.txt"
  - docker exec -it CI /bin/bash -c "python3 setup.py install"
  - docker exec -it CI /bin/bash -c "pip3 install codecov"

script:
  - docker exec -it CI /bin/bash -c "coverage run -m unittest discover tests/unit_tests *_tests.py -f"

after_success:
  - docker exec -it CI /bin/bash -c "codecov --token=2b55393b-5a8b-443d-bf55-fb06db6a7770"