# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
language: python
python:
  - "3.6"

install:
  - python3 setup.py install
  - pip3 install -r requirements.txt
  - pip3 install -r test-requirements.txt
script: python3 ./tests/unit_tests/main_test.py