# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
sudo: required

language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - docker pull shapelets/khiva
  - docker run shapelets/khiva /bin/bash

script:
  - ls
  - python setup.py install
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - python ./tests/unit_tests/main_test.py