# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: python
python:
  - "3.6"

env:
  global:
    - ARRAYFIRE=/opt/arrayfire

before_install:
  - source .CI/travis/install-intel.sh 2>&1 > /dev/null
  - source .CI/travis/install-arrayfire.sh 2>&1 > /dev/null
  - source .CI/travis/install-cmake.sh 2>&1 > /dev/null
  - source .CI/travis/install-khiva.sh 2>&1 > /dev/null

install:
  - pip3 install -r requirements.txt
  - pip3 install -r test-requirements.txt
  - python3 setup.py install

script:
  - python3 tests/unit_tests/main_test.py
